name: project

on: ["push", "workflow_dispatch"]

jobs:
  build-and-test:
    name: Build and Test
    strategy:
        fail-fast: false
        matrix:
            os: [macos-14]
            build_type: ['release']
            run-config:
                - { platform: 'iOS', xcode_version: '14.3.1', simulator: 'name=iPhone 14 Pro' }
                - { platform: 'iOS', xcode_version: '15.2', simulator: 'name=iPhone 14 Pro' }
                - { platform: 'iPadOS', xcode_version: '15.2', simulator: 'name=iPad Pro (12.9-inch) (5th generation)' }
                - { platform: 'tvOS', xcode_version: '15.2', simulator: 'name=Apple TV 4K' }

    runs-on: ${{ matrix.os }}
    env:
        DEVELOPER_DIR: /Applications/Xcode_${{ matrix.run-config['xcode_version'] }}.app/Contents/Developer
        DESTINATION: platform=${{ matrix.run-config.platform }} Simulator,${{ matrix.run-config['simulator'] }}
    steps:
        - uses: actions/checkout@v4
        - name: Brew Update
          run: |
            brew update
        - name: List Simulators
          run: |
            xcrun simctl list
        - name: Prepare shell
          run: |
            set -o pipefail
        - name: Build and Test
          run: |
            env NSUnbufferedIO=YES xcodebuild -project "Ruka.xcodeproj" -scheme "Ruka" -destination "${DESTINATION}" clean build test
