name: project

on: ["push", "workflow_dispatch"]

jobs:
    build-app:
    name: Build App
    strategy:
        fail-fast: false
        matrix:
            os: [macos-14]
            xcode: ['15.2']
            simulator: ['name=iPhone 15 Pro']
            build_type: ['release']
        exclude:
            - os: macos-11
            xcode: '13.3.1'
            - os: macos-11
            xcode: '13.4.1'

    runs-on: ${{ matrix.os }}
    env:
        DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
        DESTINATION: platform=iOS Simulator,${{ matrix.run-config['simulator'] }}
    steps:
        - uses: actions/checkout@v4
        - name: Brew Update
            run: |
            brew update
        - name: List Simulators
            run: |
            xcrun simctl list
        - name: Prepare shell
            run: |
            set -o pipefail
        - name: Build
            run: |
            env NSUnbufferedIO=YES xcodebuild -project "Ruka.xcodeproj" -scheme "Ruka" -destination "${DESTINATION}" clean build | xcbeautify

    test-App:
    name: Test App
    strategy:
        fail-fast: false
        matrix:
            os: [macos-14]
            xcode: ['15.2']
            simulator: ['name=iPhone 15 Pro']
            build_type: ['release']
        exclude:
            - os: macos-11
            xcode: '13.3.1'
            - os: macos-11
            xcode: '13.4.1'
    runs-on: ${{ matrix.os }}
    env:
        DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
        DESTINATION: "platform=iOS Simulator,${{ matrix.run-config['simulator'] }}"
    steps:
        - uses: actions/checkout@v4
        - name: Brew Update
            run: |
            brew update
        - name: List Simulators
            run: |
            xcrun simctl list
        - name: Prepare shell
            run: |
            set -o pipefail
        - name: Test
            run: |
            env NSUnbufferedIO=YES xcodebuild -project "Ruka.xcodeproj" -scheme "Ruka" -destination "${DESTINATION}" clean test | xcbeautify
